# Generated by Django 5.0.2 on 2024-03-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geohash', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='journey_planner.nodes')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='journey_planner.nodes')),
            ],
        ),
    ]
