# Generated by Django 5.0.2 on 2024-02-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='geohash',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='edges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='journey_planner.nodes')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='journey_planner.nodes')),
            ],
        ),
    ]
